require 'tao_form/components/base'
require 'tao_form/components/form_component'
require 'tao_form/components/check_box_component'
require 'tao_form/components/switch_component'
require 'tao_form/components/radio_button_component'
require 'tao_form/components/select_component'
