require 'tao_form/inputs/string_input'
require 'tao_form/inputs/numeric_input'
require 'tao_form/inputs/boolean_input'
require 'tao_form/inputs/collection_check_boxes_input'
require 'tao_form/inputs/collection_radio_buttons_input'
